### ISSUE TITLE
"TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'"

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#102]
Suppose the topology we've passed on to `TEManager` contains no `residual_bandwidth` values attached to its `links`.  This will result in an error:

```
Traceback (most recent call last):
  File "./sdx-controller/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "./sdx-controller/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "./sdx-controller/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "./sdx-controller/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./sdx-controller/venv/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "./sdx-controller/venv/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "./sdx-controller/venv/lib/python3.9/site-packages/connexion/decorators/validation.py", line 196, in wrapper
    response = function(request)
  File "./sdx-controller/venv/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "./sdx-controller/swagger_server/controllers/connection_controller.py", line 202, in place_connection
    temanager = TEManager(topology_data, connection_data)
  File "./sdx-controller/venv/lib/python3.9/site-packages/sdxdatamodel/topologymanager/temanager.py", line 43, in __init__
    self.graph = self.generate_graph_te()
  File "./sdx-controller/venv/lib/python3.9/site-packages/sdxdatamodel/topologymanager/temanager.py", line 71, in generate_graph_te
    graph = self.manager.generate_graph()
  File "./sdx-controller/venv/lib/python3.9/site-packages/sdxdatamodel/topologymanager/manager.py", line 222, in generate_graph
    edge["weight"] = 1000.0 * (1.0 / link.residual_bandwidth)
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

Related to https://github.com/atlanticwave-sdx/sdx-controller/issues/25.

**Comment by YufengXin** [comment]
This has been handled: residual_bandwidth is a percentage (0-100% of the bandwidth) and has a default value of 100%.
