### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#109]
When running sdx-controller, there's this error from pce:

```
sdx-controller_1  | INFO:swagger_server.controllers.connection_controller:Generated graph: 'Graph with 4 nodes and 5 edges', traffic matrix: 'TrafficMatrix(connection_requests=[ConnectionRequest(source=1, destination=0, required_bandwidth
=(None,), required_latency=(None,))])'
sdx-controller_1  | INFO:swagger_server.controllers.connection_controller:TESolver: <sdx.pce.load_balancing.te_solver.TESolver object at 0x7fc2f8f54c40>
sdx-controller_1  | Creating data model: #nodes: 4, #links: 5
sdx-controller_1  | request: 1
sdx-controller_1  | links: 10
sdx-controller_1  | bound 1: 4
sdx-controller_1  | bound 2: 14
sdx-controller_1  | bound 3: 15
sdx-controller_1  | r=1:m=4:n=10
sdx-controller_1  | out: (4, 10)
sdx-controller_1  | ERROR:__main__:Exception on /SDX-Controller/1.0.0/conection [POST]
sdx-controller_1  | TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
sdx-controller_1  |
sdx-controller_1  | The above exception was the direct cause of the following exception:
sdx-controller_1  |
sdx-controller_1  | Traceback (most recent call last):
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
sdx-controller_1  |     response = self.full_dispatch_request()
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
sdx-controller_1  |     rv = self.handle_user_exception(e)
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
sdx-controller_1  |     rv = self.dispatch_request()
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
sdx-controller_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
sdx-controller_1  |     response = function(request)
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
sdx-controller_1  |     response = function(request)
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/connexion/decorators/validation.py", line 196, in wrapper
sdx-controller_1  |     response = function(request)
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
sdx-controller_1  |     return function(**kwargs)
sdx-controller_1  |   File "/usr/src/app/swagger_server/controllers/connection_controller.py", line 126, in place_connection
sdx-controller_1  |     solution = solver.solve()
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/sdx/pce/load_balancing/te_solver.py", line 76, in solve                                                                                                                   
sdx-controller_1  |     data = self._create_data_model()
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/sdx/pce/load_balancing/te_solver.py", line 315, in _create_data_model                                                                                                     
sdx-controller_1  |     bwconstraints = self._lhsbw(self.tm.connection_requests, inputmatrix)
sdx-controller_1  |   File "/usr/local/lib/python3.9/site-packages/sdx/pce/load_balancing/te_solver.py", line 430, in _lhsbw                                                                                                                 
sdx-controller_1  |     bwconstraints[i][
sdx-controller_1  | ValueError: setting an array element with a sequence.
```

**Comment by sajith** [comment]
Fixed in https://github.com/atlanticwave-sdx/datamodel/pull/91.
