### ISSUE TITLE
Make `runMC_Solver()` run more reliably

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#49]
Consider this implementation of `runMC_Solver()`:

https://github.com/atlanticwave-sdx/pce/blob/65e5b0f010038690079e0b0c49b71ca86e65b165/src/LoadBalancing/MC_Solver.py#L153-L163

It attempts to load data from a couple of JSON files without error-checking. But what happens when those JSON files are not present when the function is run?

We do call `runMC_Solver()` from SDX Controller:

https://github.com/atlanticwave-sdx/sdx-controller/blob/98fe1ce51070415b3d97b39b55a664345c86bb35/swagger_server/controllers/connection_controller.py#L138

And it fails like so:

```
Traceback (most recent call last):
  File "./sdx-controller/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "./sdx-controller/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "./sdx-controller/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "./sdx-controller/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./sdx-controller/venv/lib/python3.9/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "./sdx-controller/venv/lib/python3.9/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "./sdx-controller/venv/lib/python3.9/site-packages/connexion/decorators/validation.py", line 196, in wrapper
    response = function(request)
  File "./sdx-controller/venv/lib/python3.9/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "./sdx-controller/swagger_server/controllers/connection_controller.py", line 224, in place_connection
    result = runMC_Solver()
  File "./sdx-controller/venv/lib/python3.9/site-packages/LoadBalancing/MC_Solver.py", line 158, in runMC_Solver
    output = MC_Solver(data)
  File "./sdx-controller/venv/lib/python3.9/site-packages/LoadBalancing/MC_Solver.py", line 125, in MC_Solver
    constraint_expr = [data['constraint_coeffs'][i][j] * x[j] for j in range(data['num_vars'])]
  File "./sdx-controller/venv/lib/python3.9/site-packages/LoadBalancing/MC_Solver.py", line 125, in <listcomp>
    constraint_expr = [data['constraint_coeffs'][i][j] * x[j] for j in range(data['num_vars'])]
  File "./sdx-controller/venv/lib/python3.9/site-packages/ortools/linear_solver/pywraplp.py", line 1048, in <lambda>
    lambda self, *args: getattr(VariableExpr(self), opname)(*args))
  File "./sdx-controller/venv/lib/python3.9/site-packages/ortools/linear_solver/linear_solver_natural_api.py", line 120, in __rmul__
    return ProductCst(self, cst)
  File "./sdx-controller/venv/lib/python3.9/site-packages/ortools/linear_solver/linear_solver_natural_api.py", line 179, in __init__
    raise TypeError
TypeError
```

It would be useful if we could:

 - [ ] Check that the files we attempt to open are actually opened,
 - [ ] Check that the fields we try to access in JSON and dict objects actually exist,
 - [ ] Check array bounds,
 - [ ] Throw errors when we can't proceed, and
 - [ ] Add some tests and documentation to clarify what precisely what it is that `runMC_Solver()` is supposed to do.

**Comment by sajith** [comment]
This is no longer necessary - `runMC_Solver()` has been removed in PR #83.
